name: Build and Deploy to Azure Container Apps

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  AZURE_CONTAINER_REGISTRY: amsauthapi
  CONTAINER_APP_NAME: ams-auth-api
  RESOURCE_GROUP: rg-ams-auth-service
  CONTAINER_APP_ENV: ams-auth-api-env
  ACR_LOGIN_SERVER: amsauthapi.azurecr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build
        run: dotnet build --configuration Release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Assign User Managed Identity to Container App
        run: |
          az containerapp identity assign \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --user-assigned ${{ secrets.AZURE_MANAGED_IDENTITY_ID }}

      - name: Assign Role to Managed Identity
        run: |
          az role assignment create \
            --assignee ${{ secrets.AZURE_MANAGED_IDENTITY_ID }} \
            --role "Contributor" \
            --scope /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP }}

      - name: Restart Container App to Apply Identity Changes
        run: |
          az containerapp restart --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }}

      - name: Build and Push Container Image to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.ACR_LOGIN_SERVER }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
          file: src/ams.web.api/Dockerfile

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.ACR_LOGIN_SERVER }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          environmentVariables: |
            ASPNETCORE_ENVIRONMENT=Development

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef

      - name: Apply EF Core Migrations
        run: |
          dotnet ef database update --project src/ams.service.repositories --startup-project src/ams.web.api